### ISSUE TITLE
Blase3D Short-Term Roadmap

### ISSUE THREAD

**Issue by Sujay-Shankar** [Sujay-Shankar/blase3D#1]
**BACKGROUND READING**
- [x] Read blase paper
- [x] Skim starfish paper [Link](https://ui.adsabs.harvard.edu/abs/2015ApJ...812..128C/abstract)
- [ ] Read PHOENIX paper [Link](https://ui.adsabs.harvard.edu/abs/2013A%26A...553A...6H/abstract)
- [ ] Skim sick paper [Link](https://ui.adsabs.harvard.edu/abs/2016ApJS..223....8C/abstract)
- [ ] Read perceptron brown dwarf paper [Link](https://ui.adsabs.harvard.edu/abs/2020PASP..132d4502J/abstract)

**PAPERS TO CITE**
- [ ] [Lueber23](https://ui.adsabs.harvard.edu/abs/2023arXiv230507719L/abstract)

**CODE PRIMERS**
- [x] Pytorch (install with CUDA)
- [x] Tensorboard

**Comment by SujayShankarUT** [comment]
- [ ] Make Teff, Logg, Z heatmap for one spectral line for amplitude, line width, and line shape
- [ ] Register for TACCSTER

**Comment by SujayShankarUT** [comment]
- [ ] Deal with GPU Memory (be more memory friendly)
- [ ] Need to write grid point to state dict, and in .pt name
- [ ] Create equivalent width mapping from amplitude, sigma, and gamma
- [ ] Fix Z to solar

**Comment by SujayShankarUT** [comment]
- [ ] Bake blase versions into state_dicts
- [ ] Grid range Teff (4200, 5800), Logg(3, 5)
