### ISSUE TITLE
Blase3D Roadmap V2

### ISSUE THREAD

**Issue by Sujay-Shankar** [Sujay-Shankar/blase3D#5]
Paper Priorities List:
1. Manifolds
2. Continuum
3. Lineshapes
4. Prominence

First quality metric is comparing PHOENIX reconstruction to PHOENIX native grid.
Second quality metric is comparing PHOENIX reconstruction to actual stellar data.

In our table, we need to:
- [ ] Estimate computational impact of each manifold scheme
- [ ] Estimate storage impact of each manifold scheme
- [ ] Report quality metrics
- [ ] Discuss tradeoffs accordingly

To achieve this, first we need to get blase's state dict initialization back online.
